### ISSUE TITLE
[RombaSharp/RomVaultX] Possibility of getting away from Dokan. [Suggestion]

### ISSUE THREAD

**Issue by freitagdavid** [SabreTools/SabreTools#10]
So I ran across a windows alternative to fuse that unlike dokany was built from the ground up for windows rather than just trying to bind fuse to windows. The docs say that you can use it as just a straight fuse replacement but that it also includes much faster native bindings. Figured I would drop is here since this so happens to be the only Dokan heavy project I am avidly following.

https://github.com/billziss-gh/winfsp

**Comment by mnadareski** [comment]
Just noticed this issue here. Doesn't really fit in SabreTools since RombaSharp doesn't have any virtual drive functionality at all and most likely won't. I think you already commented on RVX the same thing. If not, make an issue there and maybe one day it can be looked into.

**Comment by freitagdavid** [comment]
I was going to post this on RVX but I think the issues tab is disabled.
