### ISSUE TITLE
[Problem] Parameters with spaces are not parsed correctly

### ISSUE THREAD

**Issue by andrea-petrucci-1975** [SabreTools/SabreTools#108]
**Version**
What version are you using?
- [x] WIP release 66fda54

**Build**
What runtime version are you using?
- [ ] .NET 9.0 running on Windows 10

**Describe the issue**
SabreTools cannot handle parameters that contain spaces, even if these parameters are delimited with " or '

**Comment by mnadareski** [comment]
Possibly fixed by https://github.com/SabreTools/SabreTools/commit/709ab44a7567590a1fd698917641beae545b940f

**Comment by mnadareski** [comment]
Fixed at least on Linux, possible issues on Windows still

**Comment by mnadareski** [comment]
Something I did in the past few commits seems to have worked. Confirmed with the original command that was failing in a Windows 10 VM and on Debian.

**Comment by mnadareski** [comment]
Issue was found to be a trailing slash being handled strangely.
