### ISSUE TITLE
Converting from mame xml to other formats, samples info is lost.

### ISSUE THREAD

**Issue by bleuge** [SabreTools/SabreTools#11]
For example, sabretools -ud -lr mame2003.xml, all samples are not in resulting dat. 
I think this is because samples don't have any hashes? only a name? Maybe there is an option to ignore this behaviour?

**Comment by mnadareski** [comment]
By default, only `rom` and `disk` types are written out. If you want to include more types, use the `-rt, --item-type` flag to include samples as well. Note that if you use this, you'll need to have `-rt=rom -rt=disk -rt=sample` to get the full current output plus samples.

**Comment by bleuge** [comment]
Thank you very much!
