### ISSUE TITLE
Zip/7z takes ages and reads a lot more than is needed in d2d

### ISSUE THREAD

**Issue by edc71** [SabreTools/SabreTools#14]
a 200G set for d2d in zip takes abt 8TB read and 20 hours to complete..

lots of stream errors in the logfile, seek errors

**Comment by mnadareski** [comment]
Zip side seems to be addressed by https://github.com/SabreTools/SabreTools/commit/1de4bc7b184b9b1d519163f9b204c8ee62ba35b9

**Comment by mnadareski** [comment]
Possibly partially fixed by https://github.com/SabreTools/SabreTools/commit/ac2a9fabb7ae83037ecebb99223459ec2911319b
