### ISSUE TITLE
--add-blank-files causes OutOfMemoryException

### ISSUE THREAD

**Issue by johnsanc314** [SabreTools/SabreTools#18]
When using the add-blank-files option the files hash properly but the app hangs at the Organizing Roms step for a good 10 minutes or so before an unhandled exception occurs. There was plenty of RAM available when this occurred.

Example command:
sabretools --d2d --add-blank-files --output-type=xml --superdat "\\TOWER\Games\Computer\IBM - PC Compatibles\ScummVM"

**Comment by mnadareski** [comment]
This has been open for over a year and I think it's been fixed with some of the changes that have gone in since. Please test this out again and tell me if there's still an issue that needs investigating.

**Comment by mnadareski** [comment]
We're closing in on year 2 here. @johnsanc314 please test this out again. If I don't hear back, I'll close and mark as a wontfix.
