### ISSUE TITLE
Generating 1G1R sets, outputting as files/archives and cross-platform compatibility

### ISSUE THREAD

**Issue by andrebrait** [SabreTools/SabreTools#22]
Hi there.

I'm the author of [1G1R ROMset Generator](https://github.com/andrebrait/1g1r-romset-generator) and it started out as just a simple tool to generate 1G1R sets from No-Intro Parent/Clone DATs, but I also started receiving requests to add many pieces of functionality to it (a good chunk of which you already have, which looked like a crazy amount of work, by the way :open_mouth:).

It would likely be easier to add what my application does to yours than the other way around. However, I have a few questions:

1. Would you be open to adding the generation of 1G1R sets to this set of tools (supposing I submit a PR, for example)?
2. Are there any plans to work on making it and associated tools cross-platform? This was a number 1 priority for my tool, because I want even a Raspberry Pi to be able to run it.
3. In case number 2 answer is "no" or "not in the near future", I would like to rewrite (a good chunk of) it in Java. In this case, is the licensing really all GPLv3? You state that it's all GPLv3, but I'm asking here just in case :wink: .

Thanks in advance!

**Comment by mnadareski** [comment]
I actually added a dummy setting for 1G1R a LONG time ago but never got around to even figuring out how to properly implement it. I'd be more than happy to take a PR to add this functionality.

As for making this cross-platform, the closest to that that I'm willing to go toward is making this all .NET Core. C# is my language of choice and for better or worse, that limits where it can run natively (at least for the Framework versions, Core has a pretty broad base at this point). Honestly, the license for my code is "just include the source project in the list of included code and you're golden".

**Comment by mnadareski** [comment]
As a followup to my .NET Core comment, it looks like RPi can actually have .NET Core 3.1 installed, which is pretty neat: https://elbruno.com/2019/12/30/raspberypi-how-to-install-net-core-3-1-in-a-raspberry-pi-4/
To me, this takes away the need to do hacky things like mono or code conversion to make it run on more devices. I do want to move away from Framework as much as possible given (especially) 4.6.2 is super old now.

**Comment by andrebrait** [comment]
Got it. With .NET Core there's some hope for Linux, though a GUI would still be a big no, I suppose.

I have started a project in Java and I'll see where I can get with it to at least reproduce what I have with my current tool, but taking more inspiration from yours in some senses.

I unfortunately have cross-platform compatibility as a first priority, so even .NET Core is sorta not there yet for me.

What would it take to "port" it to Core, btw?

**Comment by mnadareski** [comment]
It's already there on .NET Core. My comment was that I wanted to phase out the older .NET Framework stuff, since that's holding back a lot of cooler programming tricks that can be done with newer revisions of C#. .NET Core 3.0+ also provides a lot of UI functionality that was missing from earlier versions, so I actually don't think that's as much of an issue.

**Comment by mnadareski** [comment]
It's already there on .NET Core. My comment was that I wanted to phase out the older .NET Framework stuff, since that's holding back a lot of cooler programming tricks that can be done with newer revisions of C#. .NET Core 3.0+ also provides a lot of UI functionality that was missing from earlier versions, so I actually don't think that's as much of an issue.

**Comment by mnadareski** [comment]
This may be a strange question, but is 1G1R (as your tool does things) the equivalent of *only* having parent sets? I see some additional filtering based on a region list as well, but the main thing seems to be the parent set part.

**Comment by andrebrait** [comment]
I don't know what you're calling a parent set. I assume it would be a set of only the parent games?

If so, that would technically be a 1G1R since it would contain one ROM for each one game, yes. 

My tool only makes it so the set can be customized by region, language, etc. (and it parses a few things from the file names because No-Intro DATs have proper names but lack the proper fields in the XML) and also it bases on what you have instead of just what the DATs and your preferences are.

**Comment by mnadareski** [comment]
Ah okay, interesting. Setting priorities for regions and the like, got it. Yes, I'm using the MAME "parent set" terminology for the `romof` and `cloneof` tags.

**Comment by andrebrait** [comment]
So, basically, what I do is:

1. Read the DAT
2. Parse Region/Language/Revision/Version/etc. from the file name (ex.: `[BIOS]` means it's a BIOS, though the DAT usually has a "isbios" attribute on the tag, it's rarely used at all, so I also parse the filename)
3. Use region to "guess" the language if no language data is found (ex.: `(USA)` likely means English as well, but `(USA) (es,fr)` clearly only means Spanish and French)
4. Group every entry in the DAT by the value of the `cloneof`/`romof` string.
5. Sort each of those lists according to user preferences. Ex.: user prefers USA over EUR ROMs, so USA come first, EUR second, then others with no clear criteria. (The user can also choose not to use their preferences as filters, so if none of the preferred regions are found, use none)
6. _Scan the user's input directory and calculate the hashes for file found there_
7. _Go over each game and cross try to find a file that matches them, from most preferred game to least preferred game_
8. _Copy the files to the output directory, uncompressing/recompressing/compressing/grouping as needed_

**Comment by mnadareski** [comment]
I added a preliminary version of the 1G1R logic in https://github.com/SabreTools/SabreTools/commit/71815ee785f68f2aef649c5ea643fab7d32d2420 It only takes care of the region preferences, not language or BIOS filtering (both of which are available as separate filters). If you can check it out and give feedback, I'd appreciate it.

**Comment by andrebrait** [comment]
@mnadareski sure thing. I'll take a look.
Superficially, it doesn't look like the most computationally efficient algorithm for filtering ROMs per region, but it should be fine.
One note on this line here: https://github.com/SabreTools/SabreTools/commit/71815ee785f68f2aef649c5ea643fab7d32d2420#diff-73a7978a77f319c10b3dfe6f39160cadR2019

No-Intro uses names like "World" for ROMs release in all 3 big regions, so choosing "USA" has to include "World" as well. I don't know the rest of your code, but if you are not also adding these other names, it might be interesting to have that. 

It seems you're not using the fields from the DATs themselves, though, right? So far I only see name parsing. But my Java eyes might miss C# stuff :)

**Comment by mnadareski** [comment]
That sort of USA == World thing would be on the users to supply, since the regions are user-supplied on run. In that case, they'd want to do `--region=World --region=USA` in that order to ensure it is the same. The fields that it's using are the `cloneof` and `romof` fields common to most DAT types, so it *is* going on that :P

**Comment by andrebrait** [comment]
I mean the region fields from the DATs :smile: 

Each `release` entry has a `region` and a `language` field. You can use them as well, but they use 3-letter codes (or 2 letters, in case of the UK), which is why I do some little conversion there.

On initialization, I load this YAML and  then I perform a conversion of names found in those regions between parenthesis and 3-letter codes using the pattern assigned. For USA, Japan and Europe, I just make the regex be `Whatever|World` and then I can parse both at the same time and so users who select USA will also be selecting World as a possible candidate, for example. 
https://github.com/andrebrait/DATROMTool/blob/2648852c5db9cb6551783c8a5456fce8b2c2d627/core/src/main/resources/config/region-data.yaml#L5

Here's the algorithm: https://github.com/andrebrait/DATROMTool/blob/e70efbde671c27d5d089382c2045688289e0daa9/core/src/main/java/io/github/datromtool/GameParser.java#L81

Maybe I should adopt your approach as well and let the users enter the region's full name (for now I only let them enter the codes, like `USA,EUR,JPN`, etc.) though this YAML is user-replaceable.

**Comment by andrebrait** [comment]
To make things fun, the names and region data from the XML often conflicts :sweat_smile: 

For the NES, with the nicest tolerance from my tool, I have the following divergences:

```
20:47:40.657 [main] WARN io.github.datromtool.GameParser - Detected regions by name do not match with the ones provided by the DAT. Difference(detected=[ASI], provided=[CHN], game=Zhong Guo Mahjong (Asia) (Unl))
20:47:40.695 [main] WARN io.github.datromtool.GameParser - Detected regions by name do not match with the ones provided by the DAT. Difference(detected=[SPA], provided=[ASI], game=Creatom (Spain) (Gluk Video) (Unl))
20:47:40.698 [main] WARN io.github.datromtool.GameParser - Detected regions by name do not match with the ones provided by the DAT. Difference(detected=[KOR], provided=[ASI], game=Dooly Bravo Land (Korea) (Unl))
20:47:40.733 [main] WARN io.github.datromtool.GameParser - Detected regions by name do not match with the ones provided by the DAT. Difference(detected=[KOR], provided=[ASI], game=Magic Kid Googoo (Korea) (Unl))
20:47:40.734 [main] WARN io.github.datromtool.GameParser - Detected regions by name do not match with the ones provided by the DAT. Difference(detected=[JPN], provided=[ASI], game=Mahjong Samit - Kabukicho Hen (Japan) (Unl))
20:47:40.735 [main] WARN io.github.datromtool.GameParser - Detected regions by name do not match with the ones provided by the DAT. Difference(detected=[EUR, JPN, USA], provided=[JPN, USA], game=Mario Bros. (World))
20:47:40.748 [main] WARN io.github.datromtool.GameParser - Detected regions by name do not match with the ones provided by the DAT. Difference(detected=[ASI], provided=[JPN], game=Sanguo Chunqiu - Sichuan Sheng (Asia) (Unl))
20:47:40.751 [main] WARN io.github.datromtool.GameParser - Detected regions by name do not match with the ones provided by the DAT. Difference(detected=[ASI], provided=[EUR, JPN, USA], game=Super 190-in-1 (Asia) (En) (Unl) (Pirate))
20:47:40.751 [main] WARN io.github.datromtool.GameParser - Detected regions by name do not match with the ones provided by the DAT. Difference(detected=[EUR, JPN, USA], provided=[JPN, USA], game=Super Mario Bros. (World) (HVC-SM))
```

**Comment by mnadareski** [comment]
So, internally to the ST code, `release` is treated as a separate item entirely. It really is only used in a few locations so I don't rely on that at all for properties of the game itself. Just due to how everything is currently setup with filters, it would be rather difficult for me to have internal mappings or anything of the sort. I'd like to hope that adding this minimal functionality would allow for scripts to fill in the extra details that they care about, such as language or filtering on `release`-specific fields.

**Comment by mnadareski** [comment]
An example of how this would be used as it stands would be:
`--update --output-type=xml --output-dir="B:\_1G1R" -1g1r --region=World --region=USA --region=Europe --region=Japan "B:\Atari - 2600 (Parent-Clone) (20200215-222027).dat"` where the region names are case-insensitive.

**Comment by mnadareski** [comment]
For the time being, since I *do* have something resembling 1G1R, I have a batch feature that can execute the other bits of filtering, and the filtering itself has been overhauled. I'll close this particular issue for now. If there are other specifics to 1G1R that are needed, a new item should be opened.
