### ISSUE TITLE
Running -ud with MAME dat, faults.

### ISSUE THREAD

**Issue by bleuge** [SabreTools/SabreTools#26]
edit1: -ud -m outputs a valid dat

It seems something is wrong with MAME dats since 1.0.2, the version I used for 0.222 worked, I ran it
with Sabretool -ud mame222.xml, and it merged it ok. 

Last Appveyor and 1.0.2 : 
Sabretools -ud mame0223.xml

> Processing 'mame0223.xml'                                                                                                                                                    
> Organizing roms by Game                                                                                                                                                      
> A total of 317088 items will be written out to 'mame0223'                                                                                                                    
> Opening file for writing: K:\0\00main\datroot\mame\mame0223_1.xml                                                                                                            
> ERROR System.InvalidOperationException: El token StartAttribute en el estado Content daría lugar a un documento XML no válido.                                               
>    en System.Xml.XmlTextWriter.AutoComplete(Token token)                                                                                                                     
>    en System.Xml.XmlTextWriter.WriteStartAttribute(String prefix, String localName, String ns)                                                                               
>    en System.Xml.XmlWriter.WriteAttributeString(String localName, String value)                                                                                              
>    en SabreTools.Library.DatFiles.Listxml.WriteStartGame(XmlTextWriter xtw, DatItem datItem) en B:\Programs\GitHub\SabreTools\SabreTools.Library\DatFiles\Listxml.cs:línea 70
> 9                                                                                                                                                                            
> ERROR System.InvalidOperationException: El token StartElement en el estado Error daría lugar a un documento XML no válido.                                                   
>    en System.Xml.XmlTextWriter.AutoComplete(Token token)                                                                                                                     
>    en System.Xml.XmlTextWriter.WriteStartElement(String prefix, String localName, String ns)                                                                                 
>    en SabreTools.Library.DatFiles.Listxml.WriteDatItem(XmlTextWriter xtw, DatItem datItem, Boolean ignoreblanks) en B:\Programs\GitHub\SabreTools\SabreTools.Library\DatFiles
> \Listxml.cs:línea 834                                                                                                                                                        
> ERROR System.InvalidOperationException: El token StartElement en el estado Error daría lugar a un documento XML no válido.                                                   
>    en System.Xml.XmlTextWriter.AutoComplete(Token token)                                                                                                                     
>    en System.Xml.XmlTextWriter.WriteStartElement(String prefix, String localName, String ns)                                                                                 
>    en SabreTools.Library.DatFiles.Listxml.WriteDatItem(XmlTextWriter xtw, DatItem datItem, Boolean ignoreblanks) en B:\Programs\GitHub\SabreTools\SabreTools.Library\DatFiles
> \Listxml.cs:línea 834                                                                                                                                                        
> ERROR System.InvalidOperationException: El token StartElement en el estado Error daría lugar a un documento XML no válido.                                                   
>    en System.Xml.XmlTextWriter.AutoComplete(Token token)                                                                                                                     
>    en System.Xml.XmlTextWriter.WriteStartElement(String prefix, String localName, String ns)                                                                                 
>    en SabreTools.Library.DatFiles.Listxml.WriteDatItem(XmlTextWriter xtw, DatItem datItem, Boolean ignoreblanks) en B:\Programs\GitHub\SabreTools\SabreTools.Library\DatFiles
> \Listxml.cs:línea 834                                                                                                                                                        
> ERROR System.InvalidOperationException: El token StartElement en el estado Error daría lugar a un documento XML no válido.                                                   
>    en System.Xml.XmlTextWriter.AutoComplete(Token token)                                                                                                                     
>    en System.Xml.XmlTextWriter.WriteStartElement(String prefix, String localName, String ns)                                                                                 
>    en SabreTools.Library.DatFiles.Listxml.WriteDatItem(XmlTextWriter xtw, DatItem datItem, Boolean ignoreblanks) en B:\Programs\GitHub\SabreTools\SabreTools.Library\DatFiles

etc,...
This is the log of the process (previous errors were not logged to .log file)
>--
hi, previous version default to merge? (I think), but the last one (using last one from Appveyor:  SabreTools v1.0.2-2020-08-02 21:52:17) outputs this:
Logging started 2020-08-07 08:48:19
Command run: K:\0\00main\datroot\mame\SabreTools.exe -ud mame0223.xml
USER - 07/08/2020 8:48:19 - Processing 'mame0223.xml'
VERBOSE - 07/08/2020 8:48:19 - Attempting to read file to get format: K:\0\00main\datroot\mame\mame0223.xml
VERBOSE - 07/08/2020 8:48:19 - Attempting to read file to get format: K:\0\00main\datroot\mame\mame0223.xml
VERBOSE - 07/08/2020 8:48:19 - Attempting to read file: K:\0\00main\datroot\mame\mame0223.xml
USER - 07/08/2020 8:48:28 - There were no items to write out!
Logging ended 2020-08-07 08:48:28
Total runtime: 00:00:08

**Comment by mnadareski** [comment]
Okay, after reading through the error above, it seems like this is an oversight in my listxml writing. I'll see what I can do to get this fixed sooner than later.

**Comment by mnadareski** [comment]
Fixed in https://github.com/SabreTools/SabreTools/commit/f27f57855d82879713188d36ad8e5fc11bc05335
