### ISSUE TITLE
Crash when trying to convert xml dat to csv

### ISSUE THREAD

**Issue by mariomadproductions** [SabreTools/SabreTools#33]
```
$sabretools --update --output-type=csv "Nintendo - Nintendo DSi (Digital) (CDN) (CDN) (20201208-120000).dat"
[...]
ERROR Error with file 'C:\Users\David\Desktop\Nintendo - Nintendo DSi (Digital)
(CDN) (CDN) (20201208-120000).dat': System.Xml.XmlException: '"' is an unexpecte
d token. The expected token is ';'. Line 9503, position 202.
[...]
```

Here is the file:
[Nintendo - Nintendo DSi (Digital) (CDN) (CDN) (20201208-120000).dat.txt](https://github.com/SabreTools/SabreTools/files/5690772/Nintendo.-.Nintendo.DSi.Digital.CDN.CDN.20201208-120000.dat.txt)

**Comment by mnadareski** [comment]
The DatFile has an invalid value in the `serial` field on line 9503. This is an issue coming from No-Intro, not with SabreTools. The instance of `&` in that line should be replaced by `&amp;`.

**Comment by mariomadproductions** [comment]
Okay. I'll see if it can be fixed on No-Intro's end.
