### ISSUE TITLE
[Bug] Missing files from DFD

### ISSUE THREAD

**Issue by Sanaki** [SabreTools/SabreTools#36]
This was reported to me by a Windows user, I just verified it using ef2b51a36a297240a74e95ee08dcf8102206c2c2. When attempting a testing d2d, files that show in the log as scanned did not actually show up in the resulting datfile. Results vary per-run. Attached log and dat were from one attempt.

[sabretools (2021-06-19 01-53-34).log](https://github.com/SabreTools/SabreTools/files/6757863/sabretools.2021-06-19.01-53-34.log)
[Atari - 2600 (2021-06-19).xml](https://github.com/SabreTools/SabreTools/files/6757865/Atari.-.2600.2021-06-19.xml.txt)
Chopper Command and Pole Position were the missing games in this dat.

Unfortunately I'm not sure what other info to provide, but I'm willing to test whatever may help pin it down.

**Comment by mnadareski** [comment]
I was able to finally verify this locally. With a smaller set of data, it also dropped 2 items. I'll investigate.
