### ISSUE TITLE
Add support for Archive.org file lists 

### ISSUE THREAD

**Issue by coughlanio** [SabreTools/SabreTools#38]
Every Archive.org collection has a `<collection>_files.xml` that contains a number of fields associated with the uploaded files:

```xml
...
<file name="CHD-PSX-Improvements/Alundra (Un-Worked Design).chd" source="original">
  <mtime>1602941664</mtime>
  <size>304609496</size>
  <md5>bca10a647b9fbaeffce18e3f4a2b1e00</md5>
  <crc32>fc2de0a3</crc32>
  <sha1>43c4673cdaf17ec2c718ae4d3db7b64596848653</sha1>
  <format>Unknown</format>
</file>
...
```
You can see an example here: https://ia801704.us.archive.org/12/items/chd_psx/chd_psx_files.xml

There's also a `<collection>_meta.xml` file that contains additional metadata related to the collection.

```xml
...
<scanner>Internet Archive HTML5 Uploader 1.6.4</scanner>
<subject>chd</subject>
<subject>redump</subject>
<subject>playstation</subject>
<subject>psx</subject>
<subject>sony</subject>
<title>CHD - Playstation (Redump)</title>
<uploader>chad.master@outlook.pt</uploader>
<publicdate>2020-09-22 02:23:29</publicdate>
<addeddate>2020-09-22 02:23:29</addeddate>
...
```
You can see an example here: https://ia801704.us.archive.org/12/items/chd_psx/chd_psx_meta.xml

Would it be possible to add support for these XML files so they can be easily converted to DATs of other formats for use in tools like RomVault? The metadata file is probably not needed, but it provides some additional information that might be useful, such as the proper title of the collection and the uploader, date etc.

**Comment by mnadareski** [comment]
The first one would be relatively easy to add, the second, since it's a separate file from the first would not be as easy, unfortunately. Normally, a single file type goes to another single file type.
