### ISSUE TITLE
I think this line is making the -ngn option do nothing

### ISSUE THREAD

**Issue by i30817** [SabreTools/SabreTools#4]
https://github.com/SabreTools/SabreTools/blob/63789d37733caa0db05916cf0d5eec40dcd07beb/SabreTools.Library/DatFiles/Filter.cs#L642

Isn't it supposed to be `bool found = FindValueInList(_notGameNames, item.MachineName);`?

like the line below at 670

				if (FindValueInList(_notRomNames, item.Name))

**Comment by mnadareski** [comment]
You would be 100% correct with that. I will be fixing that momentarily

**Comment by i30817** [comment]
Sorry to bother, but could you give me a mono build with this fix? I can't seem to manage to build it in linux.

**Comment by mnadareski** [comment]
Look in the test builds folder as linked in the readme. Any build after this was fixed should have the fix in it.
