### ISSUE TITLE
Is -f supposed to be ignored with --diff-against?

### ISSUE THREAD

**Issue by malvarenga123** [SabreTools/SabreTools#40]
The following command creates mame0234_1.dat instead of 210to234.dat.
`SabreTools.exe -ud --diff-against --base-dat="mame0210.dat" -ot=cmp -f="210to234.dat" mame0234.dat`
Is it supposed to ignore the output filename like that?

**Comment by mnadareski** [comment]
Yes, this was originally intentional that it doesn't fully function for base replacement or diff against functionality. I'll have to think about how to best allow that, since I want to ensure that the output DATs don't get odd.

**Comment by malvarenga123** [comment]
I think it might indeed be problematic with various dats being used. @mnadareski would it be possible to port the code from Logiqx's MAMEDiff to a single argument (eg. --mamediff) that could only be used with a pair of dats, thus allowing -f for the output result.

**Comment by mnadareski** [comment]
I'm probably not going to be porting an entirely extra set of code just for a 2-DAT case. I'm fairly certain I can figure out a better way to handle this internally.

**Comment by malvarenga123** [comment]
@mnadareski 1.2.0 and 1.1.2 give different results for the diff. Which one is correct?

dats were created by converting mame -listxml output with sabretools ud -ot=cmp -ip -f=2xx.dat 2xx.xml

1.1.2 log:
[sabretools (2025-05-01 17-47-49).zip](https://github.com/user-attachments/files/20004883/sabretools.2025-05-01.17-47-49.zip)
1.2.0 log:
[sabretools (2025-05-01 17-24-47).zip](https://github.com/user-attachments/files/20004903/sabretools.2025-05-01.17-24-47.zip)

Also, notice these lines:
1.2.0:
Comparing '241to275.dat' to base DAT...
Comparing '241to275.dat' to base DAT completed in 0:00:08:28.0575000

1.1.2:
Comparing '275' to base DAT...
Comparing '275' to base DAT completed in 0:00:00:03.8910000

**Comment by malvarenga123** [comment]
I just noticed that diff-against does not work with MAME's listxml output:

```
Logging started 2025-05-13 20:18:53
Command run: D:\SabreTools_net9.0_win-x86_release\SabreTools.exe ud --diff-against --base-dat=241.xml -ot=cmp -f=241to275.dat 275.xml
USER - 2025-05-13 8:18:53 PM - Processing individual DATs...
USER - 2025-05-13 8:18:53 PM - Adding DAT: D:\SabreTools_net9.0_win-x86_release\241.xml
USER - 2025-05-13 8:18:53 PM - Parsing 'D:\SabreTools_net9.0_win-x86_release\241.xml' into internal DAT...
USER - 2025-05-13 8:19:09 PM - Parsing 'D:\SabreTools_net9.0_win-x86_release\241.xml' into internal DAT completed in 0:00:00:15.9220000
USER - 2025-05-13 8:19:09 PM - Processing individual DATs completed in 0:00:00:15.9390000
USER - 2025-05-13 8:19:09 PM - Populating internal DAT...
USER - 2025-05-13 8:19:09 PM - Populating internal DAT completed in 0:00:00:00.0110000
USER - 2025-05-13 8:19:09 PM - Applying splitting to DAT...
USER - 2025-05-13 8:19:09 PM - Applying splitting to DAT completed in 0:00:00:00.0000000
USER - 2025-05-13 8:19:09 PM - Applying cleaning steps to DAT...
USER - 2025-05-13 8:19:09 PM - Applying cleaning steps to DAT completed in 0:00:00:00.0060000
USER - 2025-05-13 8:19:09 PM - Applying removals to DAT...
USER - 2025-05-13 8:19:09 PM - Applying removals to DAT completed in 0:00:00:00.0030000
USER - 2025-05-13 8:19:09 PM - Parsing 'D:\SabreTools_net9.0_win-x86_release\275.xml' into internal DAT...
USER - 2025-05-13 8:19:26 PM - Parsing 'D:\SabreTools_net9.0_win-x86_release\275.xml' into internal DAT completed in 0:00:00:16.7250000
USER - 2025-05-13 8:19:26 PM - Applying splitting to DAT...
USER - 2025-05-13 8:19:26 PM - Applying splitting to DAT completed in 0:00:00:00.0000000
USER - 2025-05-13 8:19:26 PM - Applying cleaning steps to DAT...
USER - 2025-05-13 8:19:26 PM - Applying cleaning steps to DAT completed in 0:00:00:00.0000000
USER - 2025-05-13 8:19:26 PM - Applying removals to DAT...
USER - 2025-05-13 8:19:26 PM - Applying removals to DAT completed in 0:00:00:00.0010000
USER - 2025-05-13 8:19:26 PM - Comparing '241to275.dat' to base DAT...
USER - 2025-05-13 8:19:26 PM - Comparing '241to275.dat' to base DAT completed in 0:00:00:00.0010000
USER - 2025-05-13 8:19:26 PM - There were no items to write out!
Logging ended 2025-05-13 20:19:26
Total runtime: 00:00:32

```
