### ISSUE TITLE
Softwarelists have second dataarea field

### ISSUE THREAD

**Issue by Lothrien** [SabreTools/SabreTools#43]
https://github.com/SabreTools/SabreTools/blob/8b35393d1f8ecb165f39c326aaee4bc9223e41f4/SabreTools.DatFiles/Formats/SoftwareList.cs#L339

with current solution only one line of dataarea is read.

			<dataarea name="rom" size="1048576" width="16" endianness="little">
				<rom name="mh8m256s083a.u3" size="1048576" crc="7fff2520" sha1="eb538b82c5516fae8ce38778e41fb118aa5c830f" offset="000000" />
			</dataarea>
			<dataarea name="sram" size="32768" width="16" endianness="little">

**Comment by Lothrien** [comment]
something like:
                        part.DataArea.Add(DataArea);

                        reader.Read();

**Comment by mnadareski** [comment]
Can you please link and example software list that has multiple data areas?

**Comment by Lothrien** [comment]
[wswan.txt](https://github.com/SabreTools/SabreTools/files/7232270/wswan.txt)

**Comment by Lothrien** [comment]
337
                        else
                            items.Add(dataArea);

                        // read second dataArea
                        reader.Read();

841
// add Itemtype.DataArea second time
// DataArea is not public enum
// something like
                       foreach (DateArea kvp in rom.DataArea)
                        {
                       xtw.WriteStartElement("dataarea");
                        xtw.WriteRequiredAttributeString("name", dataAreaName);
                        xtw.WriteOptionalAttributeString("size", rom.DataArea?.Size.ToString());
                        xtw.WriteOptionalAttributeString("width", rom.DataArea?.Width?.ToString());
                        xtw.WriteOptionalAttributeString("endianness", rom.DataArea?.Endianness.FromEndianness());
                        }

**Comment by Lothrien** [comment]
OK, it is not so easy

softwarelist.cs 337                                
                                   items.AddRange(roms);
                                // logger.User($"create '{string.Join(", ", roms)}' ...");
                                // "roms" not null, since dataArea contains data
                                // 2. Dataarea read as "rom" with empty rom
                                // create 'SabreTools.DatItems.Formats.Rom' ...
                                // create '' ...

So the second dataarea was dropped, since there is no format?
Must be in itemdictonary.cs...

Something the same must be with the info fields #44, because I can the them in 
itemdictonary.cs 421                 items[key].Add(value);

but they where gone in
softwarelist.cs 391
// only item.ItemType == rom

**Comment by Lothrien** [comment]
softwarelist.cs 337
                       // If we got valid roms, add them to the list
                        if (!String.IsNullOrEmpty(string.Join(", ", roms)))
                            {
                                items.AddRange(roms);
                                // logger.User($"create '{string.Join(", ", roms)}' ...");
                                // "roms" not null, since dataArea contains data
                                // 2. Dataarea read as "rom" with empty rom
                                // create 'SabreTools.DatItems.Formats.Rom' ...
                                // create '' ...
                            }
                        else
                            {
                                items.Add(dataArea);
                                //logger.User($"6create '{dataArea.Name}' ...");
                                // 6create 'sram' ...
                                // 6create 'eeprom' ...
                            }

**Comment by Lothrien** [comment]
#43 and #44 are almost solved
Machine Information was not provided, so the tag was empty.
Just looking how to move both tag to the right place, while writing.

**Comment by Lothrien** [comment]
dataarea tag has now correct position in <part>
