### ISSUE TITLE
INFO Elements were not written to file

### ISSUE THREAD

**Issue by Lothrien** [SabreTools/SabreTools#44]
https://github.com/SabreTools/SabreTools/blob/8b35393d1f8ecb165f39c326aaee4bc9223e41f4/SabreTools.DatFiles/Formats/SoftwareList.cs#L789

		<publisher>Bandai</publisher>
		<info name="serial" value="SWJ-BAN023"/>
		<info name="release" value="20000210"/>
		<info name="alt_title" value="超兄貴 男の魂札"/>
		<part name="cart" interface="wswan_cart">

output is

		<publisher>Bandai</publisher>
		<part name="cart" interface="wswan_cart">

with info elements missing

**Comment by Lothrien** [comment]
Execution of
SabreTools.exe -ud -di -ot=sl -out=new\ dats\
in dats folder are mess softwarelist, no-intro and tosec xml

**Comment by mnadareski** [comment]
Because of the `-di` flag you're using, there's a nonzero chance that those are being stripped. Can you try running the output without `-di` to see if it does the same?

**Comment by Lothrien** [comment]
without -di, still missing
[wswan_with_up_flag.txt](https://github.com/SabreTools/SabreTools/files/7232278/wswan_with_up_flag.txt)

**Comment by Lothrien** [comment]
ItemDictonary.cs 598
//logger.User($"4create '{key}' '{string.Join(", ", value)}'...");
//4create 'makaimura for wonderswan (japan)' 'SabreTools.DatItems.Formats.Rom'...
//4create 'default' 'SabreTools.DatItems.Formats.Info, SabreTools.DatItems.Formats.Info, SabreTools.DatItems.Formats.Info,...
All Info Items were sorted to 'default' in a large block. The connection to the machine or rom got lost.

**Comment by Lothrien** [comment]
`<info>` elements were written at the end of `<part>`. This is not the correct position, but working.
I tend to sort the concurrentlist in DatItems.cs, so that it and `<sharedfeat>` were sorted in front of `<rom>`

**Comment by Lothrien** [comment]
I tried 
SabreTools.exe ud -m -dd -ot=sl --base-dat=wswan.xml -out= /dats
but it is not taking wswan as base. Base in this case is the first file in /dats

Manipulating input of in /dats and adding 1wswan.xml to read this as first file. The result now contains desired function of keeping base-dat. Is that how you wanted this to work?
[DiffDAT - deduped (2021-10-03).txt](https://github.com/SabreTools/SabreTools/files/7273261/DiffDAT.-.deduped.2021-10-03.txt)

INFO Elements were not included here, but should to keep base intact.

**Comment by Lothrien** [comment]
pull requests #52 #51

**Comment by mnadareski** [comment]
Should be supported now.
