### ISSUE TITLE
[New Format] gamelist

### ISSUE THREAD

**Issue by Lothrien** [SabreTools/SabreTools#45]
`<?xml version="1.0"?>`
`<gameList>`
`  <game>`
`    <path />`
`    <name />`
`    <thumbnail />`
`    <image />`
`    <marquee />`
`    <video />`
`    <rating />`
`    <desc />`
`    <releasedate />`
`    <developer />`
`    <publisher />`
`    <genre />`
`    <players />`
`  </game>`
`</gameList>`

**Comment by mnadareski** [comment]
Link the source of this format and I'll consider it

**Comment by Lothrien** [comment]
[https://github.com/Aloshi/EmulationStation/blob/master/GAMELISTS.md](url)

**Comment by Lothrien** [comment]
I can do a pull request for #45 and #46, if you like.

**Comment by mnadareski** [comment]
Clickable link: https://github.com/Aloshi/EmulationStation/blob/master/GAMELISTS.md

**Comment by mnadareski** [comment]
I'm noticing no hash data at all is included. That is probably why I left this here to begin with. This even includes no file sizes, unlike things like the IA format. This is likely only an output format, as converting from this format will result in mostly invalid files.

**Comment by mnadareski** [comment]
I'm making an executive decision to not support this in my libraries due to the lack of hash data, even as a purely output format.
