### ISSUE TITLE
[New Format] Hyperspin

### ISSUE THREAD

**Issue by Lothrien** [SabreTools/SabreTools#46]
`<menu>`
`<header>`
`<listname>`AAE`</listname>`
`<lastlistupdate>`09/19/2016`</lastlistupdate>`
`<listversion>`1.0`</listversion>`
`<exporterversion>`HyperList XML Exporter Version 1.3 Copywrite (c) 2009-2011 William Strong`</exporterversion>`
`</header>`

`<game image="a" index="true" name="asteroid">`
`<description>`Asteroids`</description>`
`<cloneof/>`
`<crc/>`
`<manufacturer>`Atari`</manufacturer>`
`<year>`1979`</year>`
`<genre>`Shooter`</genre>`
`<rating>`HSRS - GA (General Audience)`</rating>`
`<enabled>`Yes`</enabled>`
`</game>`

**Comment by mnadareski** [comment]
Link the source of this format and I'll consider ir

**Comment by Lothrien** [comment]
[https://hyperlist.hyperspin-fe.com/index.php](url)

**Comment by mnadareski** [comment]
Clickable link: [https://hyperlist.hyperspin-fe.com/index.php](https://github.com/SabreTools/SabreTools/issues/url)

**Comment by mnadareski** [comment]
The original site for this is now dead. I will update my link above to a wayback machine link when available. From a brief overview, it appears as if there is no hash data at all. That is probably why I left this here to begin with. This even includes no file sizes, unlike things like the IA format. This is likely only an output format, as converting from this format will result in mostly invalid files.

**Comment by mnadareski** [comment]
I'm making an executive decision to not support this in my libraries due to the lack of hash data, even as a purely output format.

**Comment by Europia79** [comment]
i'm glad i read this:  I want to create a "ratings/rankings" database for searching, sorting, trimming, & filtering:  But it never occurred to me that "ratings" would conflict "age restrictions" for Movies & Games ?  lol, i think when they say "rating", that's a misnomer :P
