### ISSUE TITLE
Treating of different ROM names with same crc/sha

### ISSUE THREAD

**Issue by Lothrien** [SabreTools/SabreTools#47]
Out in All DATs (No Duplicates).xml is

rom name="mh16m256s141b.u3" size="2097152" crc="94ea6ffc" sha1="5cc59ec1687fe83ec5fb048d3dfc37849747df34" offset="000000"
...
rom name="Digimon - Ver. WonderSwan (Hong Kong).ws" size="2097152" crc="94ea6ffc" md5="d5f7fbf06c57aa50f08c14e64d2e02a2" sha1="5cc59ec1687fe83ec5fb048d3dfc37849747df34"
...
rom name="Digimon - Ver. WonderSwan (2000)(Bandai)(AS).bin" size="2097152" crc="94ea6ffc" md5="d5f7fbf06c57aa50f08c14e64d2e02a2" sha1="5cc59ec1687fe83ec5fb048d3dfc37849747df34"

**Comment by mnadareski** [comment]
Give more context please. What was the command line? How many dats and possibly which were you using?

**Comment by Lothrien** [comment]
#43,#44,#47 are connected
Command is 
SabreTools.exe -ud -di -ot=sl -out=new\ dats\
[Bandai WonderSwan - Games (TOSEC-v2021-07-25_CM).txt](https://github.com/SabreTools/SabreTools/files/7235953/Bandai.WonderSwan.-.Games.TOSEC-v2021-07-25_CM.txt)
[Bandai - WonderSwan (20210823-014702).txt](https://github.com/SabreTools/SabreTools/files/7235954/Bandai.-.WonderSwan.20210823-014702.txt)
and MESS List wswan.xml see other issues

**Comment by Lothrien** [comment]
ok, i tried
SabreTools.exe -ud -m -gdd -ot=sl -out=new\ dats\
`<info>` tags are missing, duplicated names still inside as in "SabreTools.exe -ud -di -ot=sl -out=new\ dats\".
Difference between both command are 
> name="Anchor Field 2 (1999-06-24)(Sammy)[SWJ-SUM004] (Bandai WonderSwan - Games (TOSEC-v2021-07-25_CM))" (-di)
> name="Anchor Field 2 (1999-06-24)(Sammy)[SWJ-SUM004]" (-m -gdd)
[DiffDAT - deduped (2021-09-27).txt](https://github.com/SabreTools/SabreTools/files/7236047/DiffDAT.-.deduped.2021-09-27.txt)

SabreTools.exe -ud -m -dd -ot=sl -out=new\ dats\
here all duplicates were purched, but `<feature>` and `<info>` tags are missing (#44)
[DiffDAT - deduped (2021-09-27).txt](https://github.com/SabreTools/SabreTools/files/7236051/DiffDAT.-.deduped.2021-09-27.txt)

**Comment by Lothrien** [comment]
SabreTools.exe -ud -m -dd -ot=sl -out=new\ dats\
here all duplicates were purched, but `<feature>` and `<info>` tags are missing (#44)
[DiffDAT - deduped (2021-09-27).txt](https://github.com/SabreTools/SabreTools/files/7236051/DiffDAT.-.deduped.2021-09-27.txt)

"--update --diff-against --base-dat="Path\To\Base" InDr" is not combining the dats to one file, so I did not test it - is there any parameter I missed to test?

I think this is the best tool to move DAT  ROM formats from one source to another and filter out all information thats given. Possibly making the input better than before. Adding information from different sources. I would wish the comments also to be transfered to the right place, but I can live with some "stupid" copy & paste work :).

**Comment by Lothrien** [comment]
So with #48, it should be allowed to put all different rom names into one `<dataarea>`
rom names should be shifted with current selection of "update".
