### ISSUE TITLE
[New Format] RomCenter XML(?)

### ISSUE THREAD

**Issue by Lothrien** [SabreTools/SabreTools#49]
Current format is not readable by romcenter.
XSD Definition: https://www.romcenter.com/romcenter.xsd
is it still used? 
.rdt is not documented? look like some database compressed format.

**Comment by mnadareski** [comment]
I have quite literally no context into what you're referring to with your questions here.

I don't follow RomCenter development, so if there's a newer XML version, then that will have to be accounted for in the XML code. The RomCenter format (INI-based) is entirely separate and specifically the older one that may no longer be supported by modern versions.

I have no idea if anyone uses RomCenter anymore nor do I know if anyone uses the old or new RomCenter formats.
I also have no idea what an `.rdt` file is, nor what it's used for.

**Comment by mnadareski** [comment]
Unless otherwise noted, this should already be a part of the Logiqx XML extensions already documented.
