### ISSUE TITLE
Can we have a filter 'by description' option?

### ISSUE THREAD

**Issue by i30817** [SabreTools/SabreTools#5]
Seems missing currently.

Actually, even better would be distinguishing 'resources' from 'game' in clrmamepro input. I don't know how to filter out 'resources' in the output. I put in the merge(-m) and full-non-merged (-df) to allow the 'game' entires to have complete files, but i don't know how to filter out 'resources'

**Comment by mnadareski** [comment]
In the newest versions, "resources" are treated like the "isbios="true"" flag in XML DATs, which is what it counts as. I will consider adding a "filter by description" flag in the future.
