### ISSUE TITLE
Need help about modifying (or splitting) a dat with CHD **sets** only (NO CHD files) from MAME xml

### ISSUE THREAD

**Issue by cinnamonmatexfce** [SabreTools/SabreTools#54]
Hey, just discovered this "esoteric" tool! :wink: :smiling_imp: 
Very cool piece of software, I really appreciate it. :blush:  Thanks for your work!

I'd like to obtain an outputted dat that includes **only** the CHD sets (both parents and clones) each one with its own relative files (`rom`+`bios`+`device`). I think this should be called a _Full Non-Merged_ (CHD)set, right?

Let's look at _OutRun 2 Special Tours (GDX-0014)_ set for example...
If I'm not mistaken these are all the needed sets: `chihiro.zip` (bios) + `jvs13551.zip` (device) + `segadimm.zip` (device) + `seganetw.zip` (device) + `outr2st.zip` (parent) + `outr2sto.zip` (clone) + `outr2sto/gdx-0014.chd` (CHD).

So please help me wrap my head around this because it's not what I'm looking for:
(`> SabreTools.exe -sp -ts --output-type=lx -out=dats_out\ dats_in\mame0238.xml`)
```
<machine name="outr2sto" sourcefile="chihiro.cpp" cloneof="outr2st" romof="outr2st">
		<description>OutRun 2 Special Tours (GDX-0014)</description>
		<year>2004</year>
		<manufacturer>Sega</manufacturer>
		<disk name="gdx-0014" sha1="95fa57242e3b708c134c2a34616b745d96c6c811" region="gdrom" index="0" writable="no" />
```

<br>

**What I'd like to achieve is this kind of output**:
```
<machine name="outr2sto" sourcefile="chihiro.cpp" cloneof="outr2st" romof="outr2st">
		<description>OutRun 2 Special Tours (GDX-0014)</description>
		<year>2004</year>
		<manufacturer>Sega</manufacturer>
		<biosset name="bios0" description="Chihiro Bios"/>
		<rom name="chihiro_xbox_bios.bin" merge="chihiro_xbox_bios.bin" bios="bios0" size="524288" crc="66232714" sha1="b700b0041af8f84835e45d1d1250247bf7077188" region="bios" offset="0"/>
		<rom name="fpr-23887_29lv160te.ic4" merge="fpr-23887_29lv160te.ic4" bios="bios0" size="2097152" crc="13034372" sha1="77197fba2781ed1d81402c48bd743adb26d3161a" region="mediaboard" offset="0"/>
		<rom name="fpr21042_m29w160et.bin" merge="fpr21042_m29w160et.bin" bios="bios0" size="2097152" crc="a4fcab0b" sha1="a13cf9c5cdfe8605d82150b7573652f419b30197" region="mediaboard" offset="0"/>
		<rom name="315-6351a_epc1pc8.ic2" merge="315-6351a_epc1pc8.ic2" bios="bios0" size="130817" crc="488624ea" sha1="1a607337a186415ae90b48934ce2aae81639d4de" region="others" offset="0"/>
		<rom name="ic10_g24lc64.bin" merge="ic10_g24lc64.bin" bios="bios0" size="8192" crc="cfc5e06f" sha1="3ababd4334d8d57abb22dd98bd2d347df39648d9" region="others" offset="0"/>
		<rom name="ic11_24lc024.bin" merge="ic11_24lc024.bin" bios="bios0" size="128" crc="8dc8374e" sha1="cc03a0650bfac4bf6cb66e414bbef121cba53efe" region="others" offset="2000"/>
		<rom name="pc20_g24lc64.bin" merge="pc20_g24lc64.bin" bios="bios0" size="8192" crc="7742ab62" sha1="82dad6e2a75bab4a4840dc6939462f1fb9b95101" region="others" offset="2080"/>
		<rom name="317-0396-com.pic" merge="317-0396-com.pic" size="16384" crc="f94cf26f" sha1="dd4af2b52935c7b2d8cd196ec1a30c0ef0993322" region="pic" offset="0"/>
		<disk name="gdx-0014" sha1="95fa57242e3b708c134c2a34616b745d96c6c811" region="gdrom" index="0" writable="no"/>
		<device_ref name="pentium3"/>
		<device_ref name="pci_root"/>
		<device_ref name="nv2a_host"/>
		<device_ref name="nv2a_ram"/>
		<device_ref name="mcpx_isalpc"/>
		<device_ref name="pic8259"/>
		<device_ref name="pic8259"/>
		<device_ref name="pit8254"/>
		<device_ref name="pit_counter"/>
		<device_ref name="pit_counter"/>
		<device_ref name="pit_counter"/>
		<device_ref name="ds12885ext"/>
		<device_ref name="superio_device"/>
		<device_ref name="mcpx_smbus"/>
		<device_ref name="pic16lc"/>
		<device_ref name="cx25871"/>
		<device_ref name="eeprom"/>
		<device_ref name="mcpx_ohci"/>
		<device_ref name="usb_connector"/>
		<device_ref name="ohci_hlean2131qc"/>
		<device_ref name="usb_connector"/>
		<device_ref name="ohci_hlean2131sc"/>
		<device_ref name="usb_connector"/>
		<device_ref name="usb_connector"/>
		<device_ref name="mcpx_ohci"/>
		<device_ref name="mcpx_eth"/>
		<device_ref name="mcpx_apu"/>
		<device_ref name="mcpx_ac97_audio"/>
		<device_ref name="mcpx_ac97_modem"/>
		<device_ref name="pci_bridge"/>
		<device_ref name="mcpx_ide"/>
		<device_ref name="idectrl32bm"/>
		<device_ref name="ata_slot"/>
		<device_ref name="ata_slot"/>
		<device_ref name="ide_baseboard"/>
		<device_ref name="idectrl32bm"/>
		<device_ref name="ata_slot"/>
		<device_ref name="ata_slot"/>
		<device_ref name="nv2a_agp"/>
		<device_ref name="nv2a_gpu"/>
		<device_ref name="screen"/>
		<device_ref name="jvs_master"/>
		<device_ref name="jvs13551"/>
		<device_ref name="tmp90ph44"/>
		<device_ref name="segadimm"/>
		<device_ref name="sh4le"/>
		<device_ref name="pci_root"/>
		<device_ref name="sega315_6154"/>
		<device_ref name="ide_gdrom"/>
		<device_ref name="idectrl32bm"/>
		<device_ref name="ata_slot"/>
		<device_ref name="ata_slot"/>
		<device_ref name="pic16c622"/>
		<device_ref name="24c01"/>
		<device_ref name="24c01"/>
		<device_ref name="93c46_8"/>
		<device_ref name="seganetw"/>
		<device_ref name="gdrom"/>
		<device_ref name="cdrom_image"/>
		<device_ref name="cdda"/>
		<chip type="cpu" tag="maincpu" name="Intel Pentium III" clock="733333333"/>
		<chip type="cpu" tag="837_13551:iomcu" name="Toshiba TMP90PH44" clock="10000000"/>
		<chip type="cpu" tag="rom_board:dimmcpu" name="Hitachi SH-4 (little)" clock="200000000"/>
		<chip type="cpu" tag="rom_board:pic" name="Microchip PIC16C622" clock="20000000"/>
		<chip type="audio" tag="gdrom:cdda" name="CD/DA" clock="44100"/>
		<display tag="screen" type="raster" rotate="0" width="640" height="480" refresh="60.000000" />
		<sound channels="0"/>
		<input players="2" coins="2" tilt="yes">
			<control type="joy" player="1" buttons="6" ways="8"/>
			<control type="joy" player="2" buttons="6" ways="8"/>
		</input>
		<configuration name="Full emulation" tag="rom_board:DEBUG_ONLY" mask="1">
			<confsetting name="Enabled" value="1"/>
			<confsetting name="Disabled" value="0" default="yes"/>
		</configuration>
		<configuration name="Initialized" tag="rom_board:DEBUG_ONLY" mask="2">
			<confsetting name="Yes" value="2" default="yes"/>
			<confsetting name="No" value="0"/>
		</configuration>
		<port tag=":837_13551:COINS">
		</port>
		<port tag=":A0">
		</port>
		<port tag=":A1">
		</port>
		<port tag=":A2">
		</port>
		<port tag=":A3">
		</port>
		<port tag=":A4">
		</port>
		<port tag=":A5">
		</port>
		<port tag=":A6">
		</port>
		<port tag=":A7">
		</port>
		<port tag=":P1">
		</port>
		<port tag=":P2">
		</port>
		<port tag=":TILT">
		</port>
		<port tag=":rom_board:DEBUG_ONLY">
		</port>
		<driver status="preliminary" emulation="preliminary" savestate="unsupported"/>
		<feature type="sound" status="unemulated"/>
		<device type="cdrom" tag="gdrom:image" interface="cdrom">
			<instance name="cdrom" briefname="cdrm"/>
			<extension name="chd"/>
			<extension name="cue"/>
			<extension name="toc"/>
			<extension name="nrg"/>
			<extension name="gdi"/>
			<extension name="iso"/>
			<extension name="cdr"/>
		</device>
		<slot name="pci:02.0:port3">
			<slotoption name="xbox_controller" devname="ohci_gc"/>
			<slotoption name="an2131sc" devname="ohci_hlean2131sc"/>
			<slotoption name="an2131qc" devname="ohci_hlean2131qc"/>
		</slot>
		<slot name="pci:02.0:port4">
			<slotoption name="xbox_controller" devname="ohci_gc"/>
			<slotoption name="an2131sc" devname="ohci_hlean2131sc"/>
			<slotoption name="an2131qc" devname="ohci_hlean2131qc"/>
		</slot>
		<slot name="pci:09.0:ide2:0">
		</slot>
		<slot name="pci:09.0:ide2:1">
		</slot>
	</machine>
```

**Comment by Lothrien** [comment]
did you try it? Then we could see what its printing out.
It should print out every rom with the edits in the pull request, because before there was only one rom part recognized.
the <rom> part is defined as whole at the moment, that would mean you'll get more information in this part as you want and its doubled for every part.

**Comment by cinnamonmatexfce** [comment]
I'm a bit confused...What exactly should I try?

**Comment by Lothrien** [comment]
Did you try to run the command and can you post the output of the generated file?

**Comment by cinnamonmatexfce** [comment]
> Did you try to run the command and can you post the output of the generated file?

? Ehm... Sorry maybe I keep misunderstanding... But... Output of the command is already posted right below it.

**Comment by Lothrien** [comment]
I just tried it myself. ok, you get two files (disk) and (rom)

**Comment by cinnamonmatexfce** [comment]
> I just tried it myself. ok, you get two files (disk) and (rom)

Exactly

**Comment by Lothrien** [comment]
SabreTools.exe ud -df --output-type=lx -out=dats_out\ dats_in\mame0238.xml ?

**Comment by cinnamonmatexfce** [comment]
> SabreTools.exe ud -df --output-type=lx -out=dats_out\ dats_in\mame0238.xml ?

As soon as I can I'll try and I'll let you know.

**Comment by Lothrien** [comment]
in the readme you can also set 	
 -fm=, --forcemerging=	   Set force merging
		  Set the forcemerging tag to the given value.
		  Possible values are: None, Split, Device, Merged, Nonmerged, Full
maybe somehow you get the wanted result?

**Comment by Lothrien** [comment]
DatFullNonMergedFlag is set in basearchiv, but not used anywhere

**Comment by Lothrien** [comment]
Example is taken from [http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=outr2sto](url)

**Comment by cinnamonmatexfce** [comment]
Sorry for the late responding.
I'm not understanding what you're trying to explain me, but none of your solutions is working.

**Comment by Lothrien** [comment]
i just wrote down, what i found in the code and what you want to get as result... my test also did not get your wanted result.

**Comment by mnadareski** [comment]
I had a quick read over what you're trying to do and I'm not quite sure that this is easily done (if able to be done at all). The logic train that I'm reading is as follows:

1. Create a Full Non-Merged set
2. Filter machines down to only ones that contain at least one CHD
3. Filter out CHDs

I looked through all of the current functionality but I don't think there's anything currently supported that would allow keeping a machine based on the inclusion of a specific item (step 2 above). That's an interesting feature request, if I'm reading this all correctly.

**Comment by cinnamonmatexfce** [comment]
> I had a quick read over what you're trying to do and I'm not quite sure that this is easily done (if able to be done at all). The logic train that I'm reading is as follows:
> 
> 1. Create a Full Non-Merged set
> 2. Filter machines down to only ones that contain at least one CHD
> 3. Filter out CHDs
> 
>

I'm looking for filtering all machines with at least one CHD and creating fully non merged sets. So only steps 1 and 2.

**Comment by mnadareski** [comment]
Unfortunately, that step 2 is the part where ST falters a bit. The normal path for `update` doesn't have that functionality exposed. However, there's something in the `batch` functionality that _does_ do per-machine filtering. If you can open a separate request to add per-machine filtering to `update` and link it back to this question, I'd greatly appreciate it.

**Comment by cinnamonmatexfce** [comment]
> Unfortunately, that step 2 is the part where ST falters a bit. The normal path for `update` doesn't have that functionality exposed. However, there's something in the `batch` functionality that _does_ do per-machine filtering. If you can open a separate request to add per-machine filtering to `update` and link it back to this question, I'd greatly appreciate it.

Opened #76
