### ISSUE TITLE
[Problem] `d2d` doesn't work on empty sub-dirs

### ISSUE THREAD

**Issue by mariomadproductions** [SabreTools/SabreTools#55]
```
user@pc:~/desktop/dir2dat_test$ sabretools d2d -crc -md5 -sha1 -sha256 -caf -aaf -ic --output-type=xml -ab --output-dir=.. .
Populating removals from list...
Populating removals from list completed in 0:00:00:00.0339357
Populating DAT from /home/user/desktop/dir2dat_test...
0.00%
0.00%: /home/user/desktop/dir2dat_test/2
50.00%: /home/user/desktop/dir2dat_test/1/2
100.00%: /home/user/desktop/dir2dat_test/1/1/1
Populating DAT from /home/user/desktop/dir2dat_test completed in 0:00:00:00.0442062
Applying splitting to DAT...
Applying splitting to DAT completed in 0:00:00:00.0002427
Applying cleaning steps to DAT...
Applying cleaning steps to DAT completed in 0:00:00:00.0079806
Applying removals to DAT...
Applying removals to DAT completed in 0:00:00:00.0071799
Writing out internal dat to '/home/user/desktop'...
Organizing roms by Machine
```
It seems like it gets stuck on this step.

[dir2dat_test.zip](https://github.com/SabreTools/SabreTools/files/7697698/dir2dat_test.zip)

**Comment by mnadareski** [comment]
Can you please clarify what each of the items in that structure are supposed to be?

Also, just based on the timing, I want to see if this was inadvertently fixed by https://github.com/SabreTools/SabreTools/commit/243e3507d6de3953211f59f2ebf96d2e9efd1fcf

Do you mind pulling the latest WIP build and trying that? If it's still not working, I'll investigate.

**Comment by mariomadproductions** [comment]
They are just example files, but a more realistic example would be a digital PC game, with nested folders and such.

I'll try out the WIP build.

**Comment by mariomadproductions** [comment]
Still not working, it gets stuck like before.

**Comment by mnadareski** [comment]
I tested locally on a Windows 10 machine. The changes I made to the commandline were explicitly setting the full paths to both directories. It worked as expected. It may be worth seeing if someone else running SabreTools on a Linux environment is seeing the same issue. I wonder if it has to do with directory permissions.

**Comment by mariomadproductions** [comment]
I tried using full paths, no luck. Doesn't work with mono or dotnet. I'll try and find someone else to test it.

**Comment by mariomadproductions** [comment]
Seems like its the empty folders that are causing the hang.

**Comment by mariomadproductions** [comment]
Nice, hopefully I'll try this out sometime soon.
