### ISSUE TITLE
Problems with conversions between .dat and xml file, containing & in the filename and/or description

### ISSUE THREAD

**Issue by edc71** [SabreTools/SabreTools#73]
Running a diffdat on .dat with and & in the filename (GOG.com Games, DLC & Extras) and output set to xml doesnt convert the & to `&amp;` in the header

Probably is also the case for the other xml exceptions (`&gt;`, `&gl;` etc)

Conversion of rom titles seem ok

**Comment by mnadareski** [comment]
Can you provide a sample file that exhibits this behavior?
