### ISSUE TITLE
Invalid XML file generated

### ISSUE THREAD

**Issue by laqieer** [SabreTools/SabreTools#77]
![image](https://user-images.githubusercontent.com/8841957/158425102-8b02a0d4-ba91-4b9f-81f9-4312c9dd6f1b.png)
[Link to invalid XML](https://github.com/laqieer/FE-ROM-Hack-Database/blob/d1531333a41f10681a54793502fb5f9b6c6e6025/DATs/laqieer%20-%20Fire%20Emblem%20-%20Game%20Boy%20Advance.msx.xml#L12)
[Command](https://github.com/laqieer/FE-ROM-Hack-Database/blob/d1531333a41f10681a54793502fb5f9b6c6e6025/build.ps1#L6)

**Comment by mnadareski** [comment]
A few things:
- I notice that you're outputting every single DAT type. Is there a reason for that?
- The DAT type that you're looking at is a softwarelist XML, which requires some specific information that usually isn't contained in other formats
- A sample of the input CSV would be helpful, as it can help narrow down missing data that would prohibit certain types of DAT to write properly

**Comment by laqieer** [comment]
> * I notice that you're outputting every single DAT type. Is there a reason for that?

To support [more ROM managers](https://github.com/laqieer/FE-ROM-Hack-Database/blob/543fd955ce0ff9afdcc5f84d6077c28425fd68ea/README.md?plain=1#L28).

> * The DAT type that you're looking at is a softwarelist XML, which requires some specific information that usually isn't contained in other formats

It is better to print error log or fill default info instead of output invalid XML file.

> * A sample of the input CSV would be helpful, as it can help narrow down missing data that would prohibit certain types of DAT to write properly

[Here](https://github.com/laqieer/FE-ROM-Hack-Database/blob/main/OfflineList/datas/laqieer%20-%20Fire%20Emblem%20-%20Game%20Boy%20Advance.xml).

**Comment by mnadareski** [comment]
- Most modern managers support standard XML and CMP with no issues, as far as I'm aware, but okay.
- Understandable that you feel that way. I've had some very strange users in the past :)
- That's not a CSV that you linked to, that's an OfflineList XML, unless that is what you were actually referring to.
