### ISSUE TITLE
Stdout messes up termux terminal

### ISSUE THREAD

**Issue by mariomadproductions** [SabreTools/SabreTools#81]
The stdout of SabreTools messes up the termux terminal (what you type doesn't appear). Easy workaround is to run `stty sane` after running SabreTools, which fixes the terminal, or piping the stdout to somewhere else. Using the SabreTools `--script` param doesn't make a difference.

**Comment by mnadareski** [comment]
Please provide examples of how the output is "messed up"

**Comment by mariomadproductions** [comment]
If I recall correctly, it was just that what you typed into the prompt isn't actually visible after running the command.
