### ISSUE TITLE
CRC/MD5/SHA1 incorrect when creating dats of .zip file contents 1.1.0-test_642

### ISSUE THREAD

**Issue by bstaghare** [SabreTools/SabreTools#83]
When running 1.1.0-test_642 from Appveyor, I found that creating an xml dat for the contents of a zipped (.zip) file produces bad CRC's/md5/sha1 unless the -CRC switch is used on its own (which then produces accurate CRC's).

Example:
Bad CRC's/md5/sha1 come out of this command when run against a folder with one zip file (two files in the zip): 
`sabretools --dfd "[path]\Visual Pinball [DX9] PinMame Tables [MODs, HACKs]" --output-type=xml`

Good CRC's come out with the -CRC switch added 
`sabretools --dfd "[path]Visual Pinball [DX9] PinMame Tables [MODs, HACKs]" -crc --output-type=xml`

The same bad CRC's/md5/sha1 come out if I manually add -md5 and/or -sha1 switches: 
```
sabretools --dfd "[path]Visual Pinball [DX9] PinMame Tables [MODs, HACKs]" -crc -sha1 -md5 --output-type=xml
sabretools --dfd "[path]Visual Pinball [DX9] PinMame Tables [MODs, HACKs]" -crc -md5 --output-type=xml
sabretools --dfd "[path]Visual Pinball [DX9] PinMame Tables [MODs, HACKs]" -crc -sha1 --output-type=xml
```

If I unzip the target files OR convert the zip to 7zip and run
`sabretools --dfd "[path]\Visual Pinball [DX9] PinMame Tables [MODs, HACKs]" --output-type=xml`
it produces the correct CRC's/md5/sha1.  

**So the problem appears to ONLY be with running the md5/sha1 options on the contents of zipped (.zip) files.  Unzipped or 7-zipped files produce the correct CRC's/md5/sha1**

Good CRC's/md5/sha1 from unzipped or 7-zipped files:
```
		<rom name="Junk Yard_VP9_2_2_DX9.vpt" size="22917120" crc="2d0871f9" md5="75387cae56f636f7c4c6e00cccbe6a2f" sha1="dc9e20db5b6e497169f9d0b2f0e459ae65feb998" />
		<rom name="screen_43.jpg" size="571725" crc="328047e5" md5="e11c1a6db3c8d7f938adaa5dacbe2dbd" sha1="63fa2c96cfd0e10e078e8c3b6492b4dad92b2a14" />
```
Bad CRC's/md5/sha1 from zipped file:
```
		<rom name="Junk Yard_VP9_2_2_DX9.vpt" size="22917120" crc="d8eec684" md5="8194432f49fd238723171380a46e3e1a" sha1="75c182859f23aec83d1f24bd581a4aa3a40eea7e" />
		<rom name="screen_43.jpg" size="571725" crc="1094a4e1" md5="5d9b4feef429382fc9ba653dca332279" sha1="9a0932c030f0a792a2320aaa506403c9ba011f55" />
```

**Comment by AdamJGilmore** [comment]
I am getting the exact same problem.. I'm glad I'm not alone on this!

I'm using a build cloned from the sabretools github and built in a fresh install of VS2022.  I'm using the following commands to scan a root folder that contains a single-level folder structure  with zips inside each folder.  some of the zips do contain files and also a single nested folder with uncompressed content inside (no zips in zips, anything in the zips is uncompressed).  

sabretools.exe --d2d --superdat --output-type=xml --threads=8 --no-automatic-date --name=PC98test PC98_TEST_DAT.dat D:\Downloads\_NeoKobe_test

sabretools.exe dfd --output-type=xml --threads=8 --include-crc --include-md5 --include-sha1 --include-sha256 --name=PC98test --filename=PC98_TEST_DAT.dat "D:\Downloads\NeoKobe_test"

All contents get scanned and dat builds fine, loads into RomVault and displays content fine.  The scanned content is added as a tosort to rebuild from, and 99.95% of the hashes are incorrect.

I haven't gone as far as bstaghare's troubleshooting but I'd likely see the same results at this point.

**Comment by mnadareski** [comment]
This has been determined to be related directly to .NET 6 and how it handles reads. Please try the build for https://github.com/SabreTools/SabreTools/commit/48d15ff09ca5767179f8219f1f081fdd4594b6f0 and see if that works

**Comment by AdamJGilmore** [comment]
Compiled SabreTools with build [48d15ff] with VS2022.

Scanned a multi-level nested folder structure which included zips that contained a single subfolder alongside files in the zip root. 22,751 files total, 7,980 zips and 385 folders.  CRC, MD5, SHA1, SHA256 included in scan.

Zero errors encountered during scan and dat build phase.  Loaded new dat into RomVault and rebuilt the entire structure to a new folder using the scanned folder as a source.  No errors encountered, all files accounted for. 

I would say with confidence the fix worked!  Thank you.

**Comment by mnadareski** [comment]
Awesome, thanks for reporting and testing.
