### ISSUE TITLE
[Problem] Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by AdamJGilmore** [SabreTools/SabreTools#85]
[sabretools_array_error.txt](https://github.com/SabreTools/SabreTools/files/9561601/sabretools_array_error.txt)

I was creating a d2d of a nested folder structure, nothing too complicated.  88 folders, around 30,000 zips. 

I've been using Sabretools in Windows command line, so the first time I got this error I tried it again in PowerShell, but got the exact same error output.  RAM usage was off the chart (about 16GB for 5 mins or so) during the "Organizing roms by Machine" portion, then the error hits.  A log file was generated but it was nothing but the scan portion up to and including the "organizing roms" entry, where it ends.  The remaining error output was sent to screen which is attached to this ticket.

I am completely unsure if this is a problem on my side.  I did some google-fu and found a command to see what the max array value was in powershell and came back with:
[int]::MaxValue
2147483647

Not sure if this helps.  Let me know if you need any more info!

**Comment by mnadareski** [comment]
Unfortunately, that `MaxValue` isn't always the number of elements, depending on the size of the objects you're talking about. In this case, it's probably hitting one of the other internal limits. There's little I can do about that, but I can definitely try to cap it before hitting that limit. For better or worse, this is the first time that limit has been hit by a user.

**Comment by AdamJGilmore** [comment]
Thanks for the update.  I did (a lot of) further research to try to see where this limit was being hit.. i pared down the amount of files being scanned from this large set and tried many scan attempts, but when I got into the 3,000 zip files range, I gave up.  Even if i were to split up a very large folder of files into smaller chunks and scan them then merge afterwards, I'd still be left not knowing if I'd run into this problem again during a merge operation.

Still, i'd like to be able to use SabreTools for any size folder.. I have collections in the size range of 100,000+ archive files, so this 30,000 files was only the lower limit of what I'd like to create. :)

**Comment by Lutepatious** [comment]
Could you run with "-mt=1" option? (Single Thread mode).

**Comment by AdamJGilmore** [comment]
Sorry for taking so long to respond, been busy with lots of other things.  I did find some time to look into this today and here's the results:

Single thread mode didn't help, but it was a good idea!

However, in doing some tests I did find some new results.  While the thread count didn't matter, if the folder being scanned contains even a single EMPTY FOLDER in them, this is what SabreTools seems to be getting hung up on.  I can reliably recreate the issue over and over again.

**This test instance has a total of 102 files, so the issue is NOT with the number of files being processed.**  

Test #1:
- Created a zip from a game folder, containing subfolders filled with files.  No empty folders or subfolders.  (12 folders, 102 files)
- Created a handcrafted zip with the same structure as above. (4 folders, 4 files)
result:  SabreTools processes this folder with 2 zips with no issue, within seconds, and I get a good datfile output.

Test #2:
- Created a zip from a Folder, containing subfolders filled with files.  TWO EMPTY FOLDERS left in, one a simple top-level folder that is empty, the other a top-level folder with a subfolder, both empty.  (15 folders, 102 files)
- Created a handcrafted zip with the same structure as above (6 folders, 3 files)
result:  SabreTools processes this folder with 2 zips up until "Organizing roms by Machine" and just starts chewing up ALL AVAILABLE RAM.  Process never finishes and has to be hard exited with a Ctrl-C.  

I believe the core issue is SabreTools has a problem with empty folder entries and/or the --add-blank-files option, and/or the organizing stage and blank placeholder entries.  That's my guess anyway.

I can still use SabreTools to convert a dat containing hundreds of thousands of files.. even millions of files, without issue.  But those dats being converted do not have empty folders in them.  

I'll attach the log files so you can see the folder structures and the outputs.  You can even create your own test as outlined above and meet with the same results.

[empty_folders_test_logs.zip](https://github.com/SabreTools/SabreTools/files/12785121/empty_folders_test_logs.zip)
