### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by mnadareski** [SabreTools/SabreTools#87]
We need to have a quorum of people who have contributed that their contributions can be relicensed from the current GNU GPL 3 license to a more permissive one, specifically MIT.

The following contributors need to give their explicit approval that their code contributions can be relicensed:
- @mnadareski - I give consent to relicensing by default
- @Lothrien

**Comment by Lothrien** [comment]
is it enough to tell here "I give consent to relicensing" or do I have to press some button somewhere?

**Comment by mnadareski** [comment]
That's pretty much all there is to it. No buttons, I'm not that fancy.

**Comment by mnadareski** [comment]
Was that your way of saying that you consent to relicensing? I guess I don't know if you were just asking a question or if you were stating that. Just trying to make sure I do this in the right way.

**Comment by Lothrien** [comment]
Yes, it is ok.
I give consent to relicensing

**Comment by mnadareski** [comment]
Thank you. We have a quorum among the contributors. We have chosen to relicense all existing and future code as MIT.
