### ISSUE TITLE
`--update` - Doesnt preserve MIA tag

### ISSUE THREAD

**Issue by emargee** [SabreTools/SabreTools#88]
RomVault and others are now using the `mia=yes` attribute to denote MIA roms. When using SabreTools to split a large DAT the mia tag is not preserved.

original dat has it in..
```xml
	<game name="Cool Game (Japan)">
		<category>Games</category>
		<description>Cool Game (Japan)</description>
		<rom name="Cool Game (Japan).iso" size="5185601536" crc="113cbc55" md5="175ace45b0877a1cbf64de42070d3b8f" sha1="f1913a8a7d13d03c9eed67e9b43fe63d728fd1aa" mia="yes"/>
	</game>
```
.. run `--update` command ..
```
SabreTools.exe --update --filter="machine.name:^[C].*" --output-dir="D:\Dats" --filename="C.dat" --name="System C" "original.dat"
```
Attribute is now missing ..
```xml
	<machine name="Cool Game (Japan)">
		<description>Cool Game (Japan)</description>
		<category>Games</category>
		<rom name="Cool Game (Japan).iso" size="5185601536" crc="113cbc55" md5="175ace45b0877a1cbf64de42070d3b8f" sha1="f1913a8a7d13d03c9eed67e9b43fe63d728fd1aa" />
	</machine>
```

**Comment by emargee** [comment]
@edc71 I think this should be covered by the PR. What command do you usually use to filter and I can try it out :)

**Comment by emargee** [comment]
@edc71 I had missed a bit so I've fixed it .. you can now use: 
```
 .\SabreTools.exe --update --filter="item.mia:true" --output-dir="D:\DatRoot\Custom" --filename="MIA.dat" --name="System (MIA)" "D:\RomVault351\DatRoot\Source.dat"
```
This will give you a DAT that is just MIAs .. or using `--filter="!item.mia=true"` will exclude MIAs.

**Comment by emargee** [comment]
Not quite sure why `--filter="item.mia:false"` doesnt do the opposite (or `--filter="!item.mia:true"`)

**Comment by mnadareski** [comment]
The MIA tag is officially covered at this point.
