### ISSUE TITLE
[Bug] Unsupported old entry of SoftwareList "length"

### ISSUE THREAD

**Issue by Lutepatious** [SabreTools/SabreTools#92]
Ex. nes.xml in MESS v0.144u1
----------------------------------------
	<software name="action52">
		
		<description>Action 52 (USA, Rev. A)</description>
		<year>1991</year>
		<publisher>Active Enterprises</publisher>
		<part name="cart" interface="nes_cart">
			<feature name="pcb" value="MLT-ACTION52" />
			<dataarea name="prg" size="2097152">
				<rom name="action52 pgm-a" size="524288" crc="a51212fd" sha1="746b226ffc8aa717e2f95a8bbcbdb92188a96cd2" offset="000000" />
				<rom name="action52 pgm-b" size="524288" crc="476d0b72" sha1="cf481deb81a03210e615f6bd942fe9560c102d39" offset="0x080000" />
                <rom value="0xff" length="524288" offset="0x180000" loadflag="fill" />
				<rom name="action52 pgm-c" size="524288" crc="2568dba6" sha1="da29c98c4048a9ad2ac0d5017d4368c931ebbf8e" offset="0x180000" />
			</dataarea>
			<dataarea name="chr" size="524288">
				<rom name="action52 chr-a" size="524288" crc="596442ec" sha1="dc31dc0870e393fc46494b5e386ab08e769ac514" offset="00000" />
			</dataarea>
		</part>
	</software>
----------------------------------------

nes.xml in MESS v0.144u2
----------------------------------------
	<software name="action52">
		
		<description>Action 52 (USA, Rev. A)</description>
		<year>1991</year>
		<publisher>Active Enterprises</publisher>
		<part name="cart" interface="nes_cart">
			<feature name="pcb" value="MLT-ACTION52" />
			<dataarea name="prg" size="2097152">
				<rom name="action52 pgm-a" size="524288" crc="a51212fd" sha1="746b226ffc8aa717e2f95a8bbcbdb92188a96cd2" offset="000000" />
				<rom name="action52 pgm-b" size="524288" crc="476d0b72" sha1="cf481deb81a03210e615f6bd942fe9560c102d39" offset="0x080000" />
                <rom value="0xff" size="524288" offset="0x180000" loadflag="fill" />
				<rom name="action52 pgm-c" size="524288" crc="2568dba6" sha1="da29c98c4048a9ad2ac0d5017d4368c931ebbf8e" offset="0x180000" />
			</dataarea>
			<dataarea name="chr" size="524288">
				<rom name="action52 chr-a" size="524288" crc="596442ec" sha1="dc31dc0870e393fc46494b5e386ab08e769ac514" offset="00000" />
			</dataarea>
		</part>
	</software>
----------------------------------------

modified "length" to "size".
The "length" entry exists v0.141 to v0.144u1.

**Comment by mnadareski** [comment]
Should be supported now.
