### ISSUE TITLE
[Problem] `<diskarea name="cdrom">`

### ISSUE THREAD

**Issue by Lutepatious** [SabreTools/SabreTools#95]
On current repository.
Source MAME 0.147u2 cd32.xml

	<software name="clockwsr" supported="no">
		<description>Clockwiser</description>
		<year>19??</year>
		<publisher>Rasputin</publisher>
		<part name="cdrom" interface="cd32_cdrom">
			<diskarea name="cdrom">
				<disk name="clockwiser" sha1="01a622e5b6a710eeef828b0f5807dad94de3798f"/>
			</diskarea>
		</part>
	</software>

I did simply.
SabreTools ud -out=B A

result

	<software name="clockwsr" supported="no">
		<description>Clockwiser</description>
		<year>19??</year>
		<publisher>Rasputin</publisher>
		<part name="cdrom" interface="cd32_cdrom">
			<diskarea> <=!!! name vanished !!!
				<disk name="clockwiser" sha1="01a622e5b6a710eeef828b0f5807dad94de3798f"/>
			</diskarea>
		</part>
	</software>

**Comment by mnadareski** [comment]
Please try with the latest WIP. I believe that this issue has since been fixed.
