### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kostasall12** [SabreTools/SabreTools#98]
Hello!!

I am wondering if there is a GUI version of the tool available. If not, are there any plans to release a GUI version in the future?

**Comment by mnadareski** [comment]
Nope and nope. As far as I know, nobody has bothered to make a GUI for SabreTools despite many people saying that they would. I have no intent in making a UI for SabreTools myself as a part of this project as I prefer that SabreTools is a scriptable CLI executable instead.
