### ISSUE TITLE
[BUG] Rolling release Dir2Dat incomplete name

### ISSUE THREAD

**Issue by Igneom** [SabreTools/SabreTools#99]
When creating a dat from a dir, using the following flags "SabreTools.exe d -ot=xml -orpg", it seems to not parse the names correctly, for example, this one:
```
<machine name="Phantasy Star Online Ver">
		<description>Default</description>
		<disk name="Phantasy Star Online Ver. 2 (USA) (En,Ja,Fr,De,Es)" sha1="e73977dbd733eb022467e0899e2b159c8db6cbc6" />
</machine>
```
Clearly, the name is wrong on the machine name value, but correct in the disk name value. the same doesn't happen without the -orpg flag, since it only has the disk tag.

It might be fixed already by the time someone sees this, but creating the issue anyway.

**Comment by mnadareski** [comment]
Ah, I think I see the problem. The current code should work properly for normal files but fails to account for CHDs properly. I think that this has a reasonable fix.

**Comment by mnadareski** [comment]
Try out https://github.com/SabreTools/SabreTools/commit/4b3cb481c140ddd911e7ad14c006365a49c0d196

**Comment by Igneom** [comment]
> Try out [4b3cb48](https://github.com/SabreTools/SabreTools/commit/4b3cb481c140ddd911e7ad14c006365a49c0d196)

Seems like the issue is resolved, it's outputting the name correctly now.
